<tr><td style='border:0px !important;'></td><td style='font-size:12px;background:#efefef;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='2' class='time '><p>TIME</p> </td><td style='font-size:12px;background:#efefef;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='5' rowspan='1' class='time '><p>1F</p> </td><td style='font-size:12px;background:#efefef;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='3' rowspan='1' class='time '><p>2F</p> </td><td style='font-size:12px;background:#efefef;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>3F</p> </td><td style='font-size:12px;background:#efefef;width:30px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>1F</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>101</p>
<p><span style="color: #e03e2d;">(Live)</span></p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>102</p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>103</p>
<p><span style="color: #e03e2d;">(Live)</span></p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>104</p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>105</p>
<p><span style="color: #e03e2d;">(Live)</span></p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>201</p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>202</p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>203</p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>Auditorium</p>
<p><span style="color: #e03e2d;">(Live)</span></p> </td><td style='font-size:12px;width:30px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;;' colspan='1' rowspan='1' class='time '><p>Hall B2</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>8:00</p> </td><td style='font-size:12px;background:#e6b8b7;height:150px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Pediatric'><span class="typeD">Adv</span><a href='session_detail.php?program_day=1&session_sid=1' class='viewPopup' key='1' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SF 01</p>
<p>&nbsp;</p>
<p>PD</p> <span class="typeD">Adv</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_1_1'></div></td><td style='font-size:12px;background:#d7e5b9;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Spine'><span class="typeD">Adv</span><a href='session_detail.php?program_day=1&session_sid=2' class='viewPopup' key='2' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>RC 01</p>
<p>&nbsp;</p>
<p>MS(SP)</p> <span class="typeD">Adv</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_2_2'></div></td><td style='font-size:12px;background:#d7e5b9;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Chest'><span class="type"></span><a href='session_detail.php?program_day=1&session_sid=3' class='viewPopup' key='3' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>RC 02</p>
<p>&nbsp;</p>
<p>CH</p> <span class="type"></span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_3_3'></div></td><td style='font-size:12px;background:#fdefbb;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Others'><span class="typeD">Adv</span><a href='session_detail.php?program_day=1&session_sid=4' class='viewPopup' key='4' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SS 01</p>
<p>&nbsp;</p>
<p>OT</p> <span class="typeD">Adv</span><span class="all">ENG/KOR</span></a><div style='padding-top:5px;' class='live_4_4'></div></td><td style='font-size:12px;background:#c8af8e;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Genitourinary'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=5' class='viewPopup' key='5' style='text-decoration:none;color:inherit;'><p style="position: relative; color: #c51e11; top: -22px;">Interactive</p>
<p><strong>CBR 01</strong></p>
<p>&nbsp;</p>
<p><strong>GU</strong></p> <span class="typeA">All</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_5_5'></div></td><td style='font-size:12px;background:#fdefbb;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Cardiovascular'><span class="typeD">Adv</span><a href='session_detail.php?program_day=1&session_sid=6' class='viewPopup' key='6' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SS 02</p>
<p>&nbsp;</p>
<p>CV</p> <span class="typeD">Adv</span><span class="all">ENG/KOR</span></a><div style='padding-top:5px;' class='live_6_6'></div></td><td style='font-size:12px;background:#d7e5b9;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Abdomen'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=7' class='viewPopup' key='7' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>RC 03</p>
<p>&nbsp;</p>
<p>AB</p> <span class="typeA">All</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_7_7'></div></td><td style='font-size:12px;background:#cbe7d2;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='5' class=''><a href='session_detail.php?program_day=1&session_sid=8' class='viewPopup' key='8' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>&nbsp;</p>
<p>RANK-QS</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>KSR</p> <span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_8_8'></div></td><td style='font-size:12px;background:#bfb2ca;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Neuroradiology'><a href='session_detail.php?program_day=1&session_sid=9' class='viewPopup' key='9' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>KCR Meets India</p>
<p>&nbsp;</p>
<p>NR</p> <span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_9_9'></div></td><td style='font-size:12px;width:30px !important;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='10' class=''><p></p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>8:30</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;height:40px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>9:00</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>9:30</p> </td><td style='font-size:12px;height:10px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='7' rowspan='1' class=''><p>Break (10')</p> </td><td style='font-size:12px;background:#bfb2ca;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Neuroradiology'><a href='session_detail.php?program_day=1&session_sid=10' class='viewPopup' key='10' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>KCR Meets India</p>
<p>&nbsp;</p>
<p>NR</p> <span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_10_9'></div></td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;height:100px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>10:00</p> </td><td style='font-size:12px;background:#fe385c;color:#ffffff;height:150px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='2' class='Pediatric'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=11' class='viewPopup' key='11' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>MDT 01</p>
<p>&nbsp;</p>
<p>PD</p> <span class="typeA">All</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_11_1'></div></td><td style='font-size:12px;background:#fdefbb;height:100px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='2' class='Spine'><span class="type"></span><a href='session_detail.php?program_day=1&session_sid=12' class='viewPopup' key='12' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SS 03</p>
<p>&nbsp;</p>
<p>MS(SP)</p> <span class="type"></span><span class="all">ENG/KOR</span></a><div style='padding-top:5px;' class='live_12_2'></div></td><td style='font-size:12px;background:#d7e5b9;height:100px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='2' class='Thyroid'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=13' class='viewPopup' key='13' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>RC 04</p>
<p>&nbsp;</p>
<p>TH</p> <span class="typeA">All</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_13_3'></div></td><td style='font-size:12px;background:#d7e5b9;height:100px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='2' class='Chest'><span class="type"></span><a href='session_detail.php?program_day=1&session_sid=14' class='viewPopup' key='14' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>RC 05</p>
<p>&nbsp;</p>
<p>CH</p> <span class="type"></span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_14_4'></div></td><td style='font-size:12px;background:#c8af8e;height:100px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='2' class='Cardiovascular'><span class="type"></span><a href='session_detail.php?program_day=1&session_sid=15' class='viewPopup' key='15' style='text-decoration:none;color:inherit;'><p style="position: relative; color: #c51e11; top: -22px;">Interactive</p>
<p><strong>CBR 02</strong></p>
<p>&nbsp;</p>
<p><strong>CV</strong></p> <span class="type"></span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_15_5'></div></td><td style='font-size:12px;background:#fdefbb;height:100px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='2' class='Breast'><span class="typeD">Adv</span><a href='session_detail.php?program_day=1&session_sid=16' class='viewPopup' key='16' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SS 04</p>
<p>&nbsp;</p>
<p>BR</p> <span class="typeD">Adv</span><span class="all">ENG/KOR</span></a><div style='padding-top:5px;' class='live_16_6'></div></td><td style='font-size:12px;background:#fdefbb;height:100px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='2' class='Abdomen'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=17' class='viewPopup' key='17' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SS 05</p>
<p>&nbsp;</p>
<p>AB</p> <span class="typeA">All</span><span class="all">ENG/KOR</span></a><div style='padding-top:5px;' class='live_17_7'></div></td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>10:30</p> </td><td style='font-size:12px;height:20px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class=''></td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>11:00</p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='9' rowspan='1' class=''><p>Coffee Break (20')</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>11:30</p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='8' rowspan='3' class=''></td><td style='font-size:12px;background:#5ac2a2;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='2' class=''><a href='session_detail.php?program_day=1&session_sid=133' class='viewPopup' key='133' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>Opening Session</p>
<p>&nbsp;</p>
<p>GS</p> <span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_133_9'></div></td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>12:00</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;height:50px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>12:30</p> </td><td style='font-size:12px;background:#5ac2a2;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class=''><a href='session_detail.php?program_day=1&session_sid=18' class='viewPopup' key='18' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>Congress Lecuture</p>
<p>&nbsp;</p>
<p>GS</p> <span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_18_9'></div></td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;height:10px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>13:00</p> </td><td style='font-size:12px;height:10px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='9' rowspan='1' class=''><p>Break (10')</p> </td><td style='font-size:12px;background:#595959;color:#ffffff;width:30px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='10' class=''><span style="writing-mode: vertical-rl;"><p>Scientific &amp; Technical Exhibition, Case of the Day</p> </span></td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>13:30</p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='2' rowspan='1' class=''><p></p> </td><td style='font-size:12px;background:#fc8d84;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class=''><a href='session_detail.php?program_day=1&session_sid=19' class='viewPopup' key='19' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>LS 01</p>
<p>&nbsp;</p>
<p><span style="color: #636363;">JW Medical</span></p> <span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_19_3'></div></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='5' rowspan='1' class=''><p></p> </td><td style='font-size:12px;background:#fc8d84;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class=''><a href='session_detail.php?program_day=1&session_sid=20' class='viewPopup' key='20' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>LS 02</p>
<p>&nbsp;</p>
<p><span style="color: #636363;">ClariPi Inc</span></p> <span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_20_9'></div></td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>14:00</p> </td><td style='font-size:12px;height:10px !important;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='9' rowspan='1' class=''><p>Break (20')</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>14:30</p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class=''><p></p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class=''><p></p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class=''><p></p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class=''><p></p> </td><td style='font-size:12px;background:#c8af8e;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Thyroid'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=21' class='viewPopup' key='21' style='text-decoration:none;color:inherit;'><p style="position: relative; color: #c51e11; top: -22px;">Interactive</p>
<p><strong>CBR 03</strong></p>
<p>&nbsp;</p>
<p><strong>TH</strong></p> <span class="typeA">All</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_21_5'></div></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class=''><p></p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class=''><p></p> </td><td style='font-size:12px;background:#cbe7d2;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class=''><a href='session_detail.php?program_day=1&session_sid=22' class='viewPopup' key='22' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>KSR-NECA Joint Session: AI 의료보험 Update (RINK-CR)</p>
<p>&nbsp;</p>
<p>RINK</p> <span class="kor">KOR</span></a><div style='padding-top:5px;' class='live_22_8'></div></td><td style='font-size:12px;background:#ffbf71;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class=''><a href='session_detail.php?program_day=1&session_sid=23' class='viewPopup' key='23' style='text-decoration:none;color:inherit;'><p style="position: relative; color: #c51e11; top: -22px;">Interactive</p>
<p><strong>Image Interpretation Session</strong></p> <span class="kor">KOR</span></a><div style='padding-top:5px;' class='live_23_9'></div></td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>15:00</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>15:30</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>16:00</p> </td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='9' rowspan='1' class=''><p>Break (30')</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>16:30</p> </td><td style='font-size:12px;background:#e6b8b7;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Breast'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=24' class='viewPopup' key='24' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SF 02</p>
<p>&nbsp;</p>
<p>BR</p> <span class="typeA">All</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_24_1'></div></td><td style='font-size:12px;background:#fdefbb;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Thyroid'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=25' class='viewPopup' key='25' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SS 06</p>
<p>&nbsp;</p>
<p>TH</p> <span class="typeA">All</span><span class="all">ENG/KOR</span></a><div style='padding-top:5px;' class='live_25_2'></div></td><td style='font-size:12px;background:#fe385c;color:#ffffff;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Cardiovascular'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=26' class='viewPopup' key='26' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>MDT 02</p>
<p>&nbsp;</p>
<p>CV</p> <span class="typeA">All</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_26_3'></div></td><td style='font-size:12px;background:#fdefbb;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Chest'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=27' class='viewPopup' key='27' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SS 07</p>
<p>&nbsp;</p>
<p>CH</p> <span class="typeA">All</span><span class="all">ENG/KOR</span></a><div style='padding-top:5px;' class='live_27_4'></div></td><td style='font-size:12px;background:#c8af8e;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Neuroradiology'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=28' class='viewPopup' key='28' style='text-decoration:none;color:inherit;'><p style="position: relative; color: #c51e11; top: -22px;">Interactive</p>
<p><strong>CBR 04</strong></p>
<p>&nbsp;</p>
<p><strong>NR</strong></p> <span class="typeA">All</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_28_5'></div></td><td style='font-size:12px;background:#fdefbb;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Pediatric'><span class="typeA">All</span><a href='session_detail.php?program_day=1&session_sid=29' class='viewPopup' key='29' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SS 08</p>
<p>&nbsp;</p>
<p>PD</p> <span class="typeA">All</span><span class="all">ENG/KOR</span></a><div style='padding-top:5px;' class='live_29_6'></div></td><td style='font-size:12px;background:#fdefbb;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='HeadandNeck'><span class="typeD">Adv</span><a href='session_detail.php?program_day=1&session_sid=30' class='viewPopup' key='30' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SS 09</p>
<p>&nbsp;</p>
<p>NR(HN)</p> <span class="typeD">Adv</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_30_7'></div></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class=''><p></p> </td><td style='font-size:12px;background:#e6b8b7;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='3' class='Abdomen'><span class="typeD">Adv</span><a href='session_detail.php?program_day=1&session_sid=31' class='viewPopup' key='31' style='text-decoration:none;color:inherit;'><p>&nbsp;</p>
<p>SF 03</p>
<p>&nbsp;</p>
<p>AB</p> <span class="typeD">Adv</span><span class="eng">ENG</span></a><div style='padding-top:5px;' class='live_31_9'></div></td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>17:00</p> </td><td style='font-size:12px;background:#cbe7d2;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='2' class=''><p>KSR 정기<br />평의원회</p> <span class="kor">KOR</span><div style='padding-top:5px;' class='live_132_8'></div></td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>17:30</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>18:00</p> </td><td style='font-size:12px;background:#f79646;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='10' rowspan='3' class=''><p>Welcome Reception</p>
<p>17:30-19:30</p>
<p>Auditorium Lobby, 3F, Coex</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>18:30</p> </td></tr><tr><td style='border:0px !important;'></td><td style='font-size:12px;font-family:Roboto-Bold, NotoSansKR Bold, sans-serif !important;text-align:center !important;border-bottom:1px solid #cccccc !important;border-left:1px solid #cccccc !important;' colspan='1' rowspan='1' class='time '><p>19:00</p> </td></tr>