<?php
	$_Flag['country'] = array(
		"AF" => array("cn" => "Afghanistan", "cnum" => "93"),
		"AL" => array("cn" => "Albania", "cnum" => "335"),
		"DZ" => array("cn" => "Algeria", "cnum" => "213"),
		"AS" => array("cn" => "American Samoa", "cnum" => "684"),
		"AD" => array("cn" => "Andorra", "cnum" => "376"),
		"AO" => array("cn" => "Angola", "cnum" => "244"),
		"AG" => array("cn" => "Antigua and Barbuda", "cnum" => "1-809"),
		"AR" => array("cn" => "Argentina", "cnum" => "54"),
		"AM" => array("cn" => "Armenia", "cnum" => "374"),
		"AW" => array("cn" => "Aruba", "cnum" => "297"),
		"AU" => array("cn" => "Australia", "cnum" => "61"),
		"AT" => array("cn" => "Austria", "cnum" => "43"),
		"AZ" => array("cn" => "Azerbaijan", "cnum" => "994"),
		"BS" => array("cn" => "Bahamas", "cnum" => "1-242"),
		"BH" => array("cn" => "Bahrain", "cnum" => "973"),
		"BD" => array("cn" => "Bangladesh", "cnum" => "880"),
		"BB" => array("cn" => "Barbados", "cnum" => "1-246"),
		"BY" => array("cn" => "Belarus", "cnum" => "375"),
		"BE" => array("cn" => "Belgium", "cnum" => "32"),
		"BZ" => array("cn" => "Belize", "cnum" => "501"),
		"BJ" => array("cn" => "Benin", "cnum" => "229"),
		"BM" => array("cn" => "Bermuda", "cnum" => "1-441"),
		"BT" => array("cn" => "Bhutan", "cnum" => "975"),
		"BO" => array("cn" => "Bolivia", "cnum" => "591"),
		"BA" => array("cn" => "Bosnia and Herzegovina", "cnum" => "387"),
		"BW" => array("cn" => "Botswana", "cnum" => "267"),
		"BR" => array("cn" => "Brazil", "cnum" => "55"),
		"BN" => array("cn" => "Brunei Darussalam", "cnum" => "673"),
		"BG" => array("cn" => "Bulgaria", "cnum" => "359"),
		"BF" => array("cn" => "Burkina Faso", "cnum" => "226"),
		"BI" => array("cn" => "Burundi", "cnum" => "257"),
		"KH" => array("cn" => "Cambodia", "cnum" => "855"),
		"CM" => array("cn" => "Cameroon", "cnum" => "237"),
		"CA" => array("cn" => "Canada", "cnum" => "1"),
		"CV" => array("cn" => "Cape Verde", "cnum" => "238"),
		"KY" => array("cn" => "Cayman Islands", "cnum" => "1"),
		"CF" => array("cn" => "Central African Republic", "cnum" => "236"),
		"TD" => array("cn" => "Chad", "cnum" => "235"),
		"GG" => array("cn" => "Channel Islands", "cnum" => "56"),
		"CL" => array("cn" => "Chile", "cnum" => "56"),
		"CN" => array("cn" => "China", "cnum" => "86"),
		"CO" => array("cn" => "Colombia", "cnum" => "57"),
		"KM" => array("cn" => "Comoros", "cnum" => "269"),
		"CG" => array("cn" => "Congo", "cnum" => "242"),
		"CD" => array("cn" => "Congo, The Democratic Republic of the", "cnum" => "242"),
		"CR" => array("cn" => "Costa Rica", "cnum" => "506"),
		"CI" => array("cn" => "Cote D'Ivoire", "cnum" => "225"),
		"HR" => array("cn" => "Croatia", "cnum" => "385"),
		"CU" => array("cn" => "Cuba", "cnum" => "53"),
		"CW" => array("cn" => "Curaçao", "cnum" => "420"),
		"CY" => array("cn" => "Cyprus", "cnum" => "357"),
		"CZ" => array("cn" => "Czech Republic", "cnum" => "420"),
		"DK" => array("cn" => "Denmark", "cnum" => "45"),
		"DJ" => array("cn" => "Djibouti", "cnum" => "253"),
		"DM" => array("cn" => "Dominica", "cnum" => "1-767"),
		"DO" => array("cn" => "Dominican Republic", "cnum" => "1-767"),
		"EC" => array("cn" => "Ecuador", "cnum" => "593"),
		"EG" => array("cn" => "Egypt", "cnum" => "20"),
		"SV" => array("cn" => "El Salvador", "cnum" => "503"),
		"GQ" => array("cn" => "Equatorial Guinea", "cnum" => "240"),
		"ER" => array("cn" => "Eritrea", "cnum" => "291"),
		"EE" => array("cn" => "Estonia", "cnum" => "372"),
		"ET" => array("cn" => "Ethiopia", "cnum" => "251"),
		"FO" => array("cn" => "Faroe Islands", "cnum" => "298"),
		"FJ" => array("cn" => "Fiji", "cnum" => "679"),
		"FI" => array("cn" => "Finland", "cnum" => "358"),
		"FR" => array("cn" => "France", "cnum" => "33"),
		"PF" => array("cn" => "French Polynesia", "cnum" => "689"),
		"GA" => array("cn" => "Gabon", "cnum" => "241"),
		"GM" => array("cn" => "Gambia", "cnum" => "220"),
		"GE" => array("cn" => "Georgia", "cnum" => "995"),
		"DE" => array("cn" => "Germany", "cnum" => "49"),
		"GH" => array("cn" => "Ghana", "cnum" => "233"),
		"GI" => array("cn" => "Gibraltar", "cnum" => "350"),
		"GR" => array("cn" => "Greece", "cnum" => "30"),
		"GL" => array("cn" => "Greenland", "cnum" => "299"),
		"GD" => array("cn" => "Grenada", "cnum" => "1-809"),
		"GU" => array("cn" => "Guam", "cnum" => "1"),
		"GT" => array("cn" => "Guatemala", "cnum" => "502"),
		"GN" => array("cn" => "Guinea", "cnum" => "224"),
		"GW" => array("cn" => "Guinea-Bissau", "cnum" => "245"),
		"GY" => array("cn" => "Guyana", "cnum" => "592"),
		"HT" => array("cn" => "Haiti", "cnum" => "509"),
		"HN" => array("cn" => "Honduras", "cnum" => "504"),
		"HK" => array("cn" => "Hong Kong", "cnum" => "852"),
		"HU" => array("cn" => "Hungary", "cnum" => "36"),
		"IS" => array("cn" => "Iceland", "cnum" => "354"),
		"IN" => array("cn" => "India", "cnum" => "91"),
		"ID" => array("cn" => "Indonesia", "cnum" => "62"),
		"IR" => array("cn" => "Iran, Islamic Republic of", "cnum" => "98"),
		"IQ" => array("cn" => "Iraq", "cnum" => "964"),
		"IE" => array("cn" => "Ireland", "cnum" => "353"),
		"IM" => array("cn" => "Isle of Man", "cnum" => "44-1624"),
		"IL" => array("cn" => "Israel", "cnum" => "972"),
		"IT" => array("cn" => "Italy", "cnum" => "39"),
		"JM" => array("cn" => "Jamaica", "cnum" => "1-876"),
		"JP" => array("cn" => "Japan", "cnum" => "81"),
		"JO" => array("cn" => "Jordan", "cnum" => "962"),
		"KZ" => array("cn" => "Kazakhstan", "cnum" => "7"),
		"KE" => array("cn" => "Kenya", "cnum" => "254"),
		"KI" => array("cn" => "Kiribati", "cnum" => "686"),
		"KR" => array("cn" => "Korea", "cnum" => "82"),
		"KS" => array("cn" => "Kosovo", "cnum" => "856"),
		"KW" => array("cn" => "Kuwait", "cnum" => "965"),
		"KG" => array("cn" => "Kyrgyzstan", "cnum" => "7"),
		"LA" => array("cn" => "Lao People's Democratic Republic", "cnum" => "856"),
		"LV" => array("cn" => "Latvia", "cnum" => "371"),
		"LB" => array("cn" => "Lebanon", "cnum" => "961"),
		"LS" => array("cn" => "Lesotho", "cnum" => "266"),
		"LR" => array("cn" => "Liberia", "cnum" => "231"),
		"LY" => array("cn" => "Libyan Arab Jamahiriya", "cnum" => "218"),
		"LI" => array("cn" => "Liechtenstein", "cnum" => "41-75"),
		"LT" => array("cn" => "Lithuania", "cnum" => "370"),
		"LU" => array("cn" => "Luxembourg", "cnum" => "362"),
		"MO" => array("cn" => "Macau", "cnum" => "853"),
		"MK" => array("cn" => "Macedonia", "cnum" => "389"),
		"MG" => array("cn" => "Madagascar", "cnum" => "261"),
		"MW" => array("cn" => "Malawi", "cnum" => "265"),
		"MY" => array("cn" => "Malaysia", "cnum" => "60"),
		"MV" => array("cn" => "Maldives", "cnum" => "960"),
		"ML" => array("cn" => "Mali", "cnum" => "223"),
		"MT" => array("cn" => "Malta", "cnum" => "356"),
		"MH" => array("cn" => "Marshall Islands", "cnum" => "692"),
		"MR" => array("cn" => "Mauritania", "cnum" => "222"),
		"MU" => array("cn" => "Mauritius", "cnum" => "230"),
		"YT" => array("cn" => "Mayotte", "cnum" => "269-6"),
		"MX" => array("cn" => "Mexico", "cnum" => "52"),
		"FM" => array("cn" => "Micronesia, Federated States of", "cnum" => "691"),
		"MD" => array("cn" => "Moldova, Republic of", "cnum" => "373"),
		"MC" => array("cn" => "Monaco", "cnum" => "377"),
		"MN" => array("cn" => "Mongolia", "cnum" => "976"),
		"ME" => array("cn" => "Montenegro", "cnum" => "381"),
		"MA" => array("cn" => "Morocco", "cnum" => "212"),
		"MZ" => array("cn" => "Mozambique", "cnum" => "258"),
		"MM" => array("cn" => "Myanmar", "cnum" => "95"),
		"NA" => array("cn" => "Namibia", "cnum" => "264"),
		"NP" => array("cn" => "Nepal", "cnum" => "977"),
		"NL" => array("cn" => "Netherlands", "cnum" => "31"),
		"NC" => array("cn" => "New Caledonia", "cnum" => "687"),
		"NZ" => array("cn" => "New Zealand", "cnum" => "64"),
		"NI" => array("cn" => "Nicaragua", "cnum" => "505"),
		"NE" => array("cn" => "Niger", "cnum" => "227"),
		"NG" => array("cn" => "Nigeria", "cnum" => "234"),
		"MP" => array("cn" => "Northern Mariana Islands", "cnum" => "1-670"),
		"NO" => array("cn" => "Norway", "cnum" => "47"),
		"OM" => array("cn" => "Oman", "cnum" => "968"),
		"PK" => array("cn" => "Pakistan", "cnum" => "92"),
		"PW" => array("cn" => "Palau", "cnum" => "680"),
		"PA" => array("cn" => "Panama", "cnum" => "507"),
		"PG" => array("cn" => "Papua New Guinea", "cnum" => "675"),
		"PY" => array("cn" => "Paraguay", "cnum" => "595"),
		"PE" => array("cn" => "Peru", "cnum" => "51"),
		"PH" => array("cn" => "Philippines", "cnum" => "63"),
		"PL" => array("cn" => "Poland", "cnum" => "48"),
		"PT" => array("cn" => "Portugal", "cnum" => "351"),
		"PR" => array("cn" => "Puerto Rico", "cnum" => "1-787"),
		"QA" => array("cn" => "Qatar", "cnum" => "974"),
		"RO" => array("cn" => "Romania", "cnum" => "40"),
		"RU" => array("cn" => "Russian Federation", "cnum" => "7"),
		"RW" => array("cn" => "Rwanda", "cnum" => "250"),
		"WS" => array("cn" => "Samoa", "cnum" => "685"),
		"SM" => array("cn" => "San Marino", "cnum" => "378"),
		"ST" => array("cn" => "Sao Tome and Principe", "cnum" => "239"),
		"SA" => array("cn" => "Saudi Arabia", "cnum" => "966"),
		"SN" => array("cn" => "Senegal", "cnum" => "221"),
		"RS" => array("cn" => "Serbia", "cnum" => "381"),
		"SC" => array("cn" => "Seychelles", "cnum" => "248"),
		"SL" => array("cn" => "Sierra Leone", "cnum" => "232"),
		"SG" => array("cn" => "Singapore", "cnum" => "65"),
		"SX" => array("cn" => "Sint Maarten (Dutch part)", "cnum" => "252"),
		"SK" => array("cn" => "Slovakia", "cnum" => "421"),
		"SI" => array("cn" => "Slovenia", "cnum" => "386"),
		"SB" => array("cn" => "Solomon Islands", "cnum" => "677"),
		"SO" => array("cn" => "Somalia", "cnum" => "252"),
		"ZA" => array("cn" => "South Africa", "cnum" => "27"),
		// "KR" => array("cn" => "Korea", "cnum" => "82"),
		"SS" => array("cn" => "South Sudan", "cnum" => "268"),
		"ES" => array("cn" => "Spain", "cnum" => "34"),
		"LK" => array("cn" => "Sri Lanka", "cnum" => "94"),
		"KN" => array("cn" => "St. Kitts and Nevis", "cnum" => "963"),
		"LC" => array("cn" => "St. Lucia", "cnum" => "7"),
		"MF" => array("cn" => "St. Martin (French part)", "cnum" => "255"),
		"VC" => array("cn" => "St. Vincent and the Grenadines", "cnum" => "66"),
		"SD" => array("cn" => "Sudan", "cnum" => "249"),
		"SR" => array("cn" => "Suriname", "cnum" => "597"),
		"SZ" => array("cn" => "Swaziland", "cnum" => "268"),
		"SE" => array("cn" => "Sweden", "cnum" => "46"),
		"CH" => array("cn" => "Switzerland", "cnum" => "41"),
		"SY" => array("cn" => "Syrian Arab Republic", "cnum" => "963"),
		"TW" => array("cn" => "Taiwan", "cnum" => "886"),
		"TJ" => array("cn" => "Tajikistan", "cnum" => "7"),
		"TZ" => array("cn" => "Tanzania, United Republic of", "cnum" => "255"),
		"TH" => array("cn" => "Thailand", "cnum" => "66"),
		"TL" => array("cn" => "Timor-Leste", "cnum" => "256"),
		"TG" => array("cn" => "Togo", "cnum" => "228"),
		"TO" => array("cn" => "Tonga", "cnum" => "676"),
		"TT" => array("cn" => "Trinidad and Tobago", "cnum" => "1-868"),
		"TN" => array("cn" => "Tunisia", "cnum" => "216"),
		"TR" => array("cn" => "Türkiye", "cnum" => "90"),
		"TM" => array("cn" => "Turkmenistan", "cnum" => "993"),
		"TC" => array("cn" => "Turks and Caicos Islands", "cnum" => "1"),
		"TV" => array("cn" => "Tuvalu", "cnum" => "688"),
		"UG" => array("cn" => "Uganda", "cnum" => "256"),
		"UA" => array("cn" => "Ukraine", "cnum" => "380"),
		"AE" => array("cn" => "United Arab Emirates", "cnum" => "971"),
		"GB" => array("cn" => "United Kingdom", "cnum" => "44"),
		"US" => array("cn" => "United States", "cnum" => "1"),
		"UY" => array("cn" => "Uruguay", "cnum" => "598"),
		"UZ" => array("cn" => "Uzbekistan", "cnum" => "998"),
		"VU" => array("cn" => "Vanuatu", "cnum" => "678"),
		"VE" => array("cn" => "Venezuela", "cnum" => "58"),
		"VN" => array("cn" => "Vietnam", "cnum" => "84"),
		"VI" => array("cn" => "Virgin Islands, U.S.", "cnum" => "1-809"),
		"PS" => array("cn" => "West Bank and Gaza", "cnum" => ""),
		"YE" => array("cn" => "Yemen", "cnum" => "967"),
		"ZM" => array("cn" => "Zambia", "cnum" => "260"),
		"ZW" => array("cn" => "Zimbabwe", "cnum" => "263"),
	);
?>